image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist
  before_script:
    - apt-get update -qq && apt-get install -y -qq sudo
    - sudo chmod -R 777 /usr/local/lib/node_modules
    - sudo npm install -g --unsafe-perm node-sass
    - npm install -g @angular/cli
    - npm install
  script:
    - ng build
  except:
    - tags

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apt-get update -qq && apt-get install -y -qq lftp
  script:
    - lftp -c "set sftp:auto-confirm yes; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev dist/nfl ./frontend --parallel=10 --exclude-glob .htaccess --exclude-glob .git* --exclude .git/"
